export const CURRENT_CATEGORY = 'CURRENT_CATEGORY'
export const CURRENT_TAG = 'CURRENT_TAG'

export const STORE_FETCHED_POSTS = 'STORE_FETCHED_POSTS'
export const POSTS_LOADED = 'POSTS_LOADED'
export const POST_CURRENT = 'POST_CURRENT'

export const PAGE_CURRENT = 'PAGE_CURRENT'

export const STORE_FETCHED_USER = 'STORE_FETCHED_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const INCREMENT_LOADING_PROGRESS = 'INCREMENT_LOADING_PROGRESS'
export const RESET_LOADING_PROGRESS = 'RESET_LOADING_PROGRESS'

export const PHOTO = 'PHOTO'
export const GALLERY = 'GALLERY'
export const GALLERY_INFO = 'GALLERY_INFO'
export const GALLERY_INDEX = 'GALLERY_INDEX'
export const PHOTO_SLIDESHOW = 'PHOTO_SLIDESHOW'
export const NEXT_PHOTO = 'NEXT_PHOTO'
export const PREV_PHOTO = 'PREV_PHOTO'
export const PHOTO_LIKE = 'PHOTO_LIKE'
export const LIKED = 'LIKED' 

export const HEADER_MENU = 'HEADER_MENU'